name: Deploy to staging
on:
  push:
    branches:
      - "main"

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying everything to the staging cluster
    steps:
      - run: |
          ssh -i {{ secrets.SSH_PRIVATE_KEY }} ubuntu@${{ secrets.SSH_HOST_IP }}
          cd ~/test-deployment-monorepo && git pull
          pnpm install && pnpm run build
          pm2 restart http-ws-fe
